### PR TITLE
STY: make reports work in vscode

### PR DESCRIPTION
**Pull request by GaelVaroquaux**
Two problems arose:

- Default theme is dark
- The width was set wrong

Teaser:
image

### CODE REVIEW

**Comment by emdupre** [comment]
This LGTM ! Just tried it in a Jupyter Notebook with an overlaid resampling :

Peek 2019-09-05 16-45

**Comment by emdupre** [comment]
Thank you ! :rocket:

**Comment by GaelVaroquaux** [comment]
You're jolly good at doing screen casts. You should do a blog post about the reports for the next release.

**Comment by emdupre** [comment]
Peek ! It's a great on Ubuntu. But I could definitely do a blog post :smile_cat:

**Pull request merged**
